// Political Fact-Checker Dashboard Data
// Sourced from Notion: Politics Fact-Checker Topic Tracker
// Design: Civic Transparency Portal — warm white bg, deep navy brand, verdict color spectrum
// AUTO-GENERATED — do not edit manually

export type Verdict = "True" | "Mostly True" | "Mixed" | "Mostly False" | "False";
export type Category = "Economy" | "Immigration/Border" | "Domestic Policy" | "Criminal Justice" | "Foreign Policy" | "Healthcare" | "Other";
export type Status = "Initial Coverage" | "Follow-Up Pending" | "Follow-Up Complete" | "Archived";

export interface Report {
  id: string;
  title: string;
  url: string;
  verdict: Verdict;
  category: Category;
  keyFigures: string[];
  reportDate: string;
  dateCovered: string;
  status: Status;
  followUpRequired: boolean;
  followUpReason: string;
  fullDetails: string;
  content: string;
}

export const reports: Report[] = [
  {
    id: "2f405c7c-d6a6-814e-b319-d535dbe95faa",
    title: "$2,000 tariff rebate checks do not need Congressional approval",
    url: "https://www.notion.so/2f405c7cd6a6814eb319d535dbe95faa",
    verdict: "Mostly False",
    category: "Economy",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "Week of Jan 20-26, 2026",
    dateCovered: "2026-01-26",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed he can issue \\$2,000 tariff rebate checks without Congressional approval. MOSTLY FALSE: Treasury Secretary Bessent and economic adviser Hassett both stated Congressional approval required. Constitution grants Congress power of the purse (Article I). Presidential spending requires Congressional appropriation. Sources: Forbes, Reuters",
    content: "",
  },
  {
    id: "2f405c7c-d6a6-817d-8ebf-f3af38c9a7fb",
    title: "NATO troops stayed off the frontlines in Afghanistan",
    url: "https://www.notion.so/2f405c7cd6a6817d8ebff3af38c9a7fb",
    verdict: "False",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "Week of Jan 20-26, 2026",
    dateCovered: "2026-01-26",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed NATO troops stayed off frontlines in Afghanistan. FALSE: 1,025 non-US NATO troops killed (3,486 total). For every 2 Americans killed, 1 allied soldier died. UK: 457 deaths. Canada: 165 deaths. Denmark: 44 deaths (highest per capita). NATO invoked Article 5 after 9/11 (only time in history). NATO Secretary Rutte rebutted claim. Sources: The Guardian, BBC, Reuters",
    content: "",
  },
  {
    id: "2f405c7c-d6a6-81c0-b0da-c509f192e506",
    title: "US needs ownership of Greenland to defend it",
    url: "https://www.notion.so/2f405c7cd6a681c0b0dac509f192e506",
    verdict: "Mostly False",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "Week of Jan 20-26, 2026",
    dateCovered: "2026-01-26",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed US needs ownership of Greenland to defend it. MOSTLY FALSE: US has 1951 Defense agreement granting broad military access. US operates 128 bases in 51 countries without ownership (Japan, South Korea, Germany, etc.). John Bolton called claim crazy talk. NATO Secretary confirmed existing access sufficient. Sources: NYT, [FactCheck.org](http://FactCheck.org)",
    content: "",
  },
  {
    id: "2f405c7c-d6a6-81e9-b7db-cfd2ad93124f",
    title: "Alex Pretti threatened to massacre law enforcement with a gun",
    url: "https://www.notion.so/2f405c7cd6a681e9b7dbcfd2ad93124f",
    verdict: "False",
    category: "Criminal Justice",
    keyFigures: ["Cabinet Officials"],
    reportDate: "Week of Jan 20-26, 2026",
    dateCovered: "2026-01-26",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Administration officials claimed federal agents shot Alex Pretti, a 37-year-old nurse, because he threatened to massacre law enforcement with a gun. Video evidence from CNN, BBC, ABC News frame-by-frame analysis clearly shows Pretti was holding a cell phone, not a gun. 10 shots fired in under 5 seconds. Second fatal shooting by federal agents in Minneapolis in 3 weeks. Sparked nationwide protests. Sources: CNN, BBC, ABC News, The Guardian",
    content: "",
  },
  {
    id: "2f405c7c-d6a6-81ed-9b26-d9fee80d5ccd",
    title: "No written documents prove Denmark owns Greenland",
    url: "https://www.notion.so/2f405c7cd6a681ed9b26d9fee80d5ccd",
    verdict: "False",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "Week of Jan 20-26, 2026",
    dateCovered: "2026-01-26",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed no written documents prove Denmark's ownership of Greenland. FALSE: Multiple documents exist including 1814 Treaty of Kiel, 1933 Permanent Court ruling, 1916/1941/1951/2004 US declarations recognizing Danish sovereignty. Over 200 years of documented international law. Sources: [FactCheck.org](http://FactCheck.org), Al Jazeera",
    content: "",
  },
  {
    id: "30205c7c-d6a6-8106-a520-c4e78e754251",
    title: "Inherited worst inflation in history of our country",
    url: "https://www.notion.so/30205c7cd6a68106a520c4e78e754251",
    verdict: "False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "Week of Feb 3-9, 2026",
    dateCovered: "2026-02-09",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed he inherited worst inflation in history. FALSE: When Trump took office Jan 2025, inflation was 3%, having cooled from 9.1% peak in June 2022. Fell to 2.3% in April 2025, rose to 3% in Sept 2025 after Trump tariffs. Worst inflation on record: 1980 (over 14% March-June). 1970s also saw prolonged high inflation. Trump inherited moderate 3% rate. Sources: NBC News, BLS, The Hill",
    content: "",
  },
  {
    id: "30205c7c-d6a6-81a6-ae5d-db87e67125b3",
    title: "Federal Reserve is only \"in theory\" an independent body",
    url: "https://www.notion.so/30205c7cd6a681a6ae5ddb87e67125b3",
    verdict: "Mixed",
    category: "Domestic Policy",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "Week of Feb 3-9, 2026",
    dateCovered: "2026-02-09",
    status: "Initial Coverage",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "Trump challenged Fed independence, saying only independent \"in theory.\" Said Warsh would not get job if wanted to raise rates. CONCERNING/THREATENS CONSTITUTIONAL NORMS: DOJ investigation of Fed over building renovations seen as intimidation. Trump falsely claimed \\$3-4B cost (actual: \\$2.5B, not taxpayer funded). Bipartisan criticism. Senators wont approve Warsh until resolved. Threatens institutional integrity. Sources: NBC News, Reuters, Bloomberg",
    content: "",
  },
  {
    id: "30205c7c-d6a6-81a9-8a45-cc1988e5fc9e",
    title: "Did not see racist portion of Obama video before posting",
    url: "https://www.notion.so/30205c7cd6a681a98a45cc1988e5fc9e",
    verdict: "False",
    category: "Other",
    keyFigures: ["Trump"],
    reportDate: "Week of Feb 3-9, 2026",
    dateCovered: "2026-02-09",
    status: "Initial Coverage",
    followUpRequired: true,
    followUpReason: "Extremely Controversial",
    fullDetails: "Trump claimed he \"didnt see\" racist content in video depicting Obamas as apes. HIGHLY QUESTIONABLE/LIKELY FALSE: Video posted late night (Trumps typical posting time). White House story changed: defense \u2192 staffer error \u2192 no apology. Trump said \"I didnt make a mistake.\" Deleted only after GOP senators called. Bipartisan condemnation from Lawler, LaLota, Ricketts, Wicker. Pattern: 2025 AI video of Obama arrest, altered Jeffries images. Sources: CNN, PBS, multiple lawmakers",
    content: "",
  },
  {
    id: "30205c7c-d6a6-81ae-a323-cdb3b556d36f",
    title: "Factory construction is up by 41%",
    url: "https://www.notion.so/30205c7cd6a681aea323cdb3b556d36f",
    verdict: "False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "Week of Feb 3-9, 2026",
    dateCovered: "2026-02-09",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed factory construction up 41%. FALSE: Census Bureau data shows manufacturing construction spending DECLINED 6.7% from Q4 2024 to Q3 2025. Spending fell for 9 consecutive months through Dec 2025. Trump cherry-picked comparison to pandemic low (April 2020). Under Biden: 212% increase, peaked at \\$235.6B in 2024 (CHIPS Act). Economists attribute current levels to CHIPS Act; Trump tariffs drove up construction costs. Sources: [FactCheck.org](http://FactCheck.org), Census Bureau, KPMG",
    content: "",
  },
  {
    id: "30205c7c-d6a6-81b1-ad93-c6b047d08fb3",
    title: "$18 trillion being invested into the country",
    url: "https://www.notion.so/30205c7cd6a681b1ad93c6b047d08fb3",
    verdict: "False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "Week of Feb 3-9, 2026",
    dateCovered: "2026-02-09",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed \\$18 trillion in new investment. FALSE/HIGHLY MISLEADING: White House own website shows only \\$9.6 trillion. Bloomberg Economics found \\$2.5 trillion are NOT investments, \\$3.5 trillion from opaque sovereign pledges. \\$250 billion announced before Trump took office. Many commitments long-term and subject to change. Trump doubled his own administration figure. Sources: NBC News, Bloomberg Economics, CNN, PBS",
    content: "",
  },
  {
    id: "2ed05c7c-d6a6-8110-88e6-c4bfcff9bbe5",
    title: "Trump fired Fed Governor Lisa Cook over mortgage fraud",
    url: "https://www.notion.so/2ed05c7cd6a6811088e6c4bfcff9bbe5",
    verdict: "Mostly False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "January 19, 2026",
    dateCovered: "2026-01-19",
    status: "Follow-Up Complete",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "Trump announced firing of Fed Governor Lisa Cook in Aug 2025, accusing her of mortgage fraud. Federal courts blocked the removal. Supreme Court heard arguments Jan 21, 2026 and appeared deeply skeptical of Trump's authority. All 9 justices (liberal and conservative) expressed doubts. Justice Kavanaugh warned this would weaken Fed independence. First attempt to fire Fed governor in 112-year history. Court likely to rule against Trump, rendering firing legally void. Sources: NPR, The Guardian, SCOTUSblog",
    content: "",
  },
  {
    id: "2ed05c7c-d6a6-812f-b2b4-dcdaa0d8415c",
    title: "ICE agent shot and killed Renee Good in Minneapolis",
    url: "https://www.notion.so/2ed05c7cd6a6812fb2b4dcdaa0d8415c",
    verdict: "True",
    category: "Criminal Justice",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "January 19, 2026",
    dateCovered: "2026-01-19",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Extremely Controversial",
    fullDetails: "ICE agent Jonathan Ross shot Renee Good (37, mother of 3) on January 7, 2026 in Minneapolis. Confirmed by official reports, 911 transcripts, videos. Ross fired multiple times at close range while Good was in vehicle. Videos show Ross out of vehicle's path when firing. Sparked protests, federal tear gas response hospitalized 2 children. DOJ announced Jan 19 it will not investigate shooting.",
    content: "",
  },
  {
    id: "2ed05c7c-d6a6-8157-ab0b-d52673b46dff",
    title: "DOJ investigating Minnesota Gov. Walz and Mayor Frey for obstruction",
    url: "https://www.notion.so/2ed05c7cd6a68157ab0bd52673b46dff",
    verdict: "True",
    category: "Criminal Justice",
    keyFigures: ["Trump", "State Officials"],
    reportDate: "January 19, 2026",
    dateCovered: "2026-01-19",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "DOJ investigating Minnesota Gov. Tim Walz and Minneapolis Mayor Jacob Frey for possible obstruction of federal law enforcement. Investigation confirmed by multiple news outlets. Centers on ICE operations during immigration crackdown. Both officials condemn probe as politically motivated. Represents escalation of Trump administration tensions with Democratic leaders.",
    content: "",
  },
  {
    id: "2ed05c7c-d6a6-81b5-a79c-dffb3d26ba8a",
    title: "Trump claims Russian and Chinese military vessels surround Greenland",
    url: "https://www.notion.so/2ed05c7cd6a681b5a79cdffb3d26ba8a",
    verdict: "False",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "January 19, 2026",
    dateCovered: "2026-01-19",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed Russian destroyers, Chinese destroyers, and Russian submarines are 'all over the place' around Greenland. Multiple Arctic security experts refuted this claim. Andreas \u00d8sthagen stated 'There are no Russian and Chinese ships all over the place around Greenland.' Greenland officials confirmed no awareness of such activity. Russia operates in Barents Sea, China/Russia presence in Bering Sea, not around Greenland.",
    content: "",
  },
  {
    id: "2ed05c7c-d6a6-81bb-aa4f-f874fc74e76f",
    title: "Trump considering tariffs on countries opposing Greenland annexation",
    url: "https://www.notion.so/2ed05c7cd6a681bbaa4ff874fc74e76f",
    verdict: "True",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "January 19, 2026",
    dateCovered: "2026-01-19",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump announced January 18 he is considering sanctions and 10% tariff increase against European nations rejecting US claim to Greenland. Tariffs threatened for February. European allies united in opposition, accuse Trump of 'blackmail.' Thousands marched in Nuuk and Copenhagen against annexation. Trump also floated military force as option.",
    content: "",
  },
  {
    id: "2ed05c7c-d6a6-81db-9f11-dec87a4457ba",
    title: "US military operation removed Nicol\u00e1s Maduro from power in Venezuela",
    url: "https://www.notion.so/2ed05c7cd6a681db9f11dec87a4457ba",
    verdict: "True",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "January 19, 2026",
    dateCovered: "2026-01-19",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "US military launched strikes across Venezuela on January 3, 2026, capturing Nicol\u00e1s Maduro. Trump administration justified under UN Charter Article 51 (self-defense). Venezuela now led by Delcy Rodr\u00edguez. Trump claims Venezuela 'stole' US oil rights. Legal framing allowed Trump to act unilaterally without Congress. Highly controversial internationally.",
    content: "",
  },
  {
    id: "2fb05c7c-d6a6-8182-beb3-e0438e056d7a",
    title: "ICE Targeting \"Worst of the Worst\" Criminals",
    url: "https://www.notion.so/2fb05c7cd6a68182beb3e0438e056d7a",
    verdict: "Mostly False",
    category: "Immigration/Border",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "Feb 2, 2026",
    dateCovered: "2026-01-28",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "The Trump administration claims its immigration enforcement is primarily focused on arresting and deporting the worst violent criminals. However, ICE data shows the percentage of arrestees with no criminal record has more than doubled from 21.9% to over 42% by January 2026. The administration's claim of a 70% criminal arrest rate conflates pending charges with convictions. Independent analyses show the vast majority of individuals in ICE detention have no criminal conviction, and only a small fraction have violent convictions.",
    content: "",
  },
  {
    id: "2fb05c7c-d6a6-8191-ae10-d3788ca03796",
    title: "Tariff Revenue Can Fund Multiple Major Initiatives",
    url: "https://www.notion.so/2fb05c7cd6a68191ae10d3788ca03796",
    verdict: "False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "Feb 2, 2026",
    dateCovered: "2026-01-20",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claims tariff revenue would easily pay for multiple initiatives including \\$500B military budget increase, paying down national debt, and \\$2,000 dividend checks. Total additional revenue from new tariffs is projected at \\$230 billion annually. The proposed initiatives would cost well over \\$1 trillion. The 2025 tariff revenue would cover less than half of just one of these proposals. Fundamental contradiction: tariffs need high imports for revenue but stated goal is to reduce imports.",
    content: "",
  },
  {
    id: "2fb05c7c-d6a6-81f5-a3cc-d5eb3edf0075",
    title: "Venezuela Boat Strikes Save 25,000 American Lives Each",
    url: "https://www.notion.so/2fb05c7cd6a681f5a3ccd5eb3edf0075",
    verdict: "False",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "Feb 2, 2026",
    dateCovered: "2025-10-19",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump stated every boat strike saves 25,000 American lives. Administration provided no evidence boats were carrying drugs. Total U.S. drug overdose deaths in most recent year was approximately 73,000. Trump's math would imply 5 boat strikes prevented 125,000 deaths, nearly double the annual total. Drug policy experts confirm there is no scientific method to equate drug seizures to lives saved. Primary source of fentanyl is Mexico, not Venezuela.",
    content: "",
  },
  {
    id: "2fb05c7c-d6a6-81fa-bd57-c4c7e80d03cd",
    title: "U.S. Leading China \"By a Lot\" in Artificial Intelligence",
    url: "https://www.notion.so/2fb05c7cd6a681fabd57c4c7e80d03cd",
    verdict: "Mixed",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "Feb 2, 2026",
    dateCovered: "2026-01-29",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claims U.S. is leading China by a lot in AI. U.S. does hold a lead in AI, particularly in advanced semiconductor design and manufacturing. However, description of lead as being a lot is an overstatement. Numerous experts, including White House AI czar and CEOs of Nvidia and Google DeepMind, characterize U.S. lead over China as being a matter of months, typically 3 to 18 months, not years. China possesses significant advantages in talent pool, data availability, and government investment.",
    content: "",
  },
  {
    id: "30905c7c-d6a6-8138-be33-d701eea07f3b",
    title: "Trump: Stagflation Under Biden, High Growth Under Trump",
    url: "https://www.notion.so/30905c7cd6a68138be33d701eea07f3b",
    verdict: "Mostly False",
    category: "Economy",
    keyFigures: ["Trump", "Biden"],
    reportDate: "Feb 16, 2026",
    dateCovered: "2026-01-30",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Claim: U.S. experienced stagflation under Biden, now seeing virtually no inflation and extraordinarily high growth under Trump. Analysis: Mischaracterizes both administrations. Biden had high inflation with strong GDP growth and low unemployment (not stagflation). Trump GDP growth 2.5% vs Biden last 2 years 2.9%. Inflation 2.7% not virtually zero.",
    content: "**Claim:** The U.S. experienced \"stagflation\" under President Biden, but is now seeing \"virtually no inflation and extraordinarily high economic growth\" under President Trump. (Jan 21 & 30, 2026)\n**Verdict:** Mostly False\n**Analysis:** This claim mischaracterizes the economic performance of both administrations. Stagflation requires high inflation with stagnant growth and rising unemployment. Biden had high inflation but also strong GDP growth and low unemployment. Trump GDP growth averaged 2.5% annualized vs 2.9% during Biden's last two years. Inflation averaged 2.7%, above Fed's 2% target.\n**Sources:**\n- [FactCheck.org](http://FactCheck.org) (Feb 11, 2026)\n- Heritage Foundation analysis\n- Brookings Institution analysis\n**Key Figures:** Trump, Biden\n**Category:** Economy",
  },
  {
    id: "30905c7c-d6a6-8146-aabd-d7cd77ad4ea2",
    title: "Pennsylvania Mail-In Ballot Fraud (2020)",
    url: "https://www.notion.so/30905c7cd6a68146aabdd7cd77ad4ea2",
    verdict: "False",
    category: "Domestic Policy",
    keyFigures: ["Trump"],
    reportDate: "Feb 16, 2026",
    dateCovered: "2026-02-10",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Claim: Pennsylvania sent out 1.8M mail-in ballots but received 2.5M in 2020 election. Analysis: Long-debunked misinformation. Conflates primary (1.8M sent) with general election (2.5M received). Official records show 2.6M sent, 2.27M returned for general election.",
    content: "**Claim:** In the 2020 election, \"Pennsylvania sent out 1,823,148 mail-in ballots but received back around 2.5 MILLION mail-in ballots.\" - Social Media Post, amplified by Elon Musk and Donald Trump (Feb 8-10, 2026)\n**Verdict:** False\n**Analysis:** This is a long-debunked piece of misinformation from November 2020. It falsely conflates data from two different elections: 1.8M sent (2020 primary) vs 2.5M received (2020 general). Official PA records show 2.6M ballots sent and 2.27M returned for the general election.\n**Sources:**\n- [FactCheck.org](http://FactCheck.org) (Feb 13, 2026)\n- Pennsylvania Department of State official records\n**Key Figures:** Trump\n**Category:** Domestic Policy (Elections)",
  },
  {
    id: "30905c7c-d6a6-818a-bf9d-feb78b24b601",
    title: "Trump: U.S. Crime Rate at 125-Year Low",
    url: "https://www.notion.so/30905c7cd6a6818abf9dfeb78b24b601",
    verdict: "Mixed",
    category: "Criminal Justice",
    keyFigures: ["Trump"],
    reportDate: "Feb 16, 2026",
    dateCovered: "2026-02-08",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Claim: The crime rate now is the lowest it has been since 1900. Analysis: While the murder/homicide rate is projected to be at a 65+ year low, the overall crime rate claim is an overstatement due to data comparability issues.",
    content: "**Claim:** \"The crime rate now is the lowest it has been since 1900. That is 125 years.\" - Donald Trump (Jan 29 - Feb 8, 2026)\n**Verdict:** Mixed (Half True)\n**Analysis:** While the murder/homicide rate is projected to be at a 65+ year low (potentially lowest since 1900), the overall \"crime rate\" claim is an overstatement. Data comparability issues exist for pre-1960 FBI data.\n**Sources:**\n- WRAL Fact Check (Feb 13, 2026)\n- Council on Criminal Justice Year-End 2025 Report  \n- Jeff Asher crime data analysis\n**Key Figures:** Donald Trump\n**Category:** Criminal Justice",
  },
  {
    id: "2da05c7c-d6a6-8144-9a04-c2198b826fda",
    title: "CIA drone strike on Venezuelan port facility",
    url: "https://www.notion.so/2da05c7cd6a681449a04c2198b826fda",
    verdict: "True",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "December 31, 2025",
    dateCovered: "2025-12-31",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "CIA conducted first known U.S. land-based strike inside Venezuela, targeting port facility allegedly used for drug trafficking. Confirmed by multiple credible sources.",
    content: "",
  },
  {
    id: "2da05c7c-d6a6-8172-816e-fbce58f22507",
    title: "Border crossings at record lows",
    url: "https://www.notion.so/2da05c7cd6a68172816efbce58f22507",
    verdict: "Mostly False",
    category: "Immigration/Border",
    keyFigures: ["Trump"],
    reportDate: "December 31, 2025",
    dateCovered: "2025-12-31",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump administration claims illegal border crossings hit record lows. While FY25 shows 76% drop to 691,906 encounters, this is not a 50-year low. FY17 had 526,901 encounters.",
    content: "",
  },
  {
    id: "2da05c7c-d6a6-8190-a0ac-d4f8efdd0574",
    title: "Trump pledges support for Israeli strikes on Iran",
    url: "https://www.notion.so/2da05c7cd6a68190a0acd4f8efdd0574",
    verdict: "True",
    category: "Foreign Policy",
    keyFigures: ["Trump", "Netanyahu"],
    reportDate: "December 31, 2025",
    dateCovered: "2025-12-31",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump stated he would support Israeli strikes on Iran if it rebuilds missile or nuclear programs. Made during Dec 29 meeting with Netanyahu at Mar-a-Lago.",
    content: "",
  },
  {
    id: "2da05c7c-d6a6-81a4-b466-e6b47d5b5742",
    title: "Trump administration freezes Minnesota child care funding over fraud",
    url: "https://www.notion.so/2da05c7cd6a681a4b466e6b47d5b5742",
    verdict: "Mixed",
    category: "Domestic Policy",
    keyFigures: ["Trump", "State Officials"],
    reportDate: "December 31, 2025",
    dateCovered: "2025-12-31",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "HHS froze child care payments to Minnesota citing fraud. While fraud exists and is documented, investigations began under Biden administration. Timing appears politically motivated.",
    content: "",
  },
  {
    id: "2da05c7c-d6a6-81ce-965b-fdedd7ba480b",
    title: "Trump pardoned 1,500 January 6 defendants",
    url: "https://www.notion.so/2da05c7cd6a681ce965bfdedd7ba480b",
    verdict: "True",
    category: "Criminal Justice",
    keyFigures: ["Trump"],
    reportDate: "December 31, 2025",
    dateCovered: "2025-12-31",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump issued mass pardon to 1,500-1,600 individuals charged in Jan 6 Capitol attack on first day of second term. Unprecedented use of pardon power.",
    content: "",
  },
  {
    id: "30905c7c-d6a6-813e-a8d1-c186b6fe69e5",
    title: "New Stimulus Checks and $2,000 Tariff Dividend",
    url: "https://www.notion.so/30905c7cd6a6813ea8d1c186b6fe69e5",
    verdict: "Mostly False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "2026-02-23",
    dateCovered: "2026-02-16",
    status: "Follow-Up Complete",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "FOLLOW-UP (Feb 23, 2026): SCOTUS 6-3 ruling (Feb 20) struck down IEEPA tariffs, removing the primary revenue source for any tariff dividend. No new stimulus checks authorized by Congress for 2026. Last checks issued in 2021. Fox 5 Atlanta confirmed Feb 20 that all such claims are false. Tariff dividend concept now even less viable. Claim remains Mostly False. No further follow-up needed unless new legislation introduced.",
    content: "**Claim:** The federal government is issuing new stimulus checks in February 2026, and a \\$2,000 \"tariff dividend\" will be paid to Americans.\n**Verdict:** Mostly False\n**Analysis:** There are no new, universal federal stimulus payments authorized by Congress for February 2026. The last round was in 2021. The \\$2,000 \"tariff dividend\" remains a proposal with no final plan or legislative backing. Tax Foundation analysis shows projected tariff revenues would be insufficient to fund such a program. JEC report calculated tariffs have cost average households \\$1,200, not generated dividends.\n**Sources:**\n- FOX 5 DC (Feb 16, 2026)\n- Tax Foundation analysis (Nov 2025)\n- Joint Economic Committee report\n**Key Figures:** Trump\n**Category:** Economy\n**Follow-Up:** Monitor if tariff dividend plan is formally proposed or if Congress considers legislation",
  },
  {
    id: "30905c7c-d6a6-81b5-a920-f68f7ae851cb",
    title: "Trump Can Impose Voter ID by Executive Order",
    url: "https://www.notion.so/30905c7cd6a681b5a920f68f7ae851cb",
    verdict: "Mostly False",
    category: "Domestic Policy",
    keyFigures: ["Trump"],
    reportDate: "2026-02-23",
    dateCovered: "2026-02-13",
    status: "Follow-Up Complete",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "FOLLOW-UP (Feb 23, 2026): SAVE America Act passed House (Feb 11) with all R + 1 D votes. Senate faces 60-vote filibuster threshold. Prior Trump EO on proof-of-citizenship blocked by courts. Dem AGs preparing legal challenges. Claim remains Mostly False. Next follow-up: March 9, 2026.",
    content: "**Claim:** \"There will be Voter I.D. for the Midterm Elections, whether approved by Congress or not!\" - Donald Trump (Feb 13, 2026)\n**Verdict:** Mostly False / Legally Dubious\n**Analysis:** This assertion is legally and constitutionally problematic. The U.S. Constitution's Elections Clause grants states primary authority to administer elections. In January 2026, a federal judge issued a permanent injunction against a similar executive order, ruling that the president \"lacks the authority to direct such changes.\" Any new attempt would almost certainly be blocked by courts.\n**Sources:**\n- Democracy Docket (Feb 13, 2026)\n- The Guardian (Feb 13, 2026)\n- Federal court rulings (Jan 2026)\n**Key Figures:** Trump\n**Category:** Domestic Policy (Elections)\n**Follow-Up:** Monitor if executive order is issued and subsequent legal challenges",
  },
  {
    id: "31005c7c-d6a6-810d-be22-d722a1f9698c",
    title: "DOGE Will Send $5,000 Dividend Checks to American Taxpayers",
    url: "https://www.notion.so/31005c7cd6a6810dbe22d722a1f9698c",
    verdict: "False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "2026-02-23",
    dateCovered: "2026-02-18",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "Viral claim that DOGE will send \\$5,000 checks to taxpayers. Originated from Azoria CEO James Fishback on X (Feb 18). Musk replied Will check with the President. Trump mentioned 20% of DOGE savings to citizens at FII Summit (Feb 19). No legislation or EO exists. DOGE savings (\\~\\$110B claimed) are widely disputed. SCOTUS tariff ruling further undermines revenue basis. Sources: Mashable, USA Today, Wharton.",
    content: "## Claim\nDOGE will send \\$5,000 dividend checks to American taxpayers from federal spending savings. \u2014 Viral social media; echoed by Trump at FII Summit, February 19, 2026.\n## Verdict: False\nNo legislation, executive order, or official government program authorizes such payments. The proposal originated from a social media post by Azoria CEO James Fishback on February 18, 2026. Musk replied Will check with the President, and Trump mentioned the concept the next day. The checks are contingent on DOGE achieving \\$2 trillion in savings \u2014 a target repeatedly revised downward and far from realized. DOGE reported savings (\\~\\$110B) are widely disputed. The SCOTUS tariff ruling further undermines the revenue basis.\n## Sources\n- Mashable (Feb 23, 2026): [https://mashable.com/article/doge-dividend-checks-real-elon-musk](https://mashable.com/article/doge-dividend-checks-real-elon-musk)\n- USA Today (Feb 22, 2026): [https://www.usatoday.com/story/news/nation/2026/02/22/grants-contracts-cut-elon-musk-doge-usaid/88218628007/](https://www.usatoday.com/story/news/nation/2026/02/22/grants-contracts-cut-elon-musk-doge-usaid/88218628007/)\n- Wharton Budget Model (Feb 20, 2026): [https://budgetmodel.wharton.upenn.edu/issues/2026/2/20/supreme-court-tariff-ruling-ieepa-revenue-and-potential-refunds](https://budgetmodel.wharton.upenn.edu/issues/2026/2/20/supreme-court-tariff-ruling-ieepa-revenue-and-potential-refunds)",
  },
  {
    id: "31005c7c-d6a6-814d-ab73-f532379d8eec",
    title: "Trump Claims Economic Growth Is Exploding to Numbers Unheard Of",
    url: "https://www.notion.so/31005c7cd6a6814dab73f532379d8eec",
    verdict: "Mostly False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "2026-02-23",
    dateCovered: "2026-01-27",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed economic growth is exploding to numbers unheard of. BEA data shows Q4 2025 GDP grew only 1.4% (annualized), down from 4.4% in Q3. Full-year 2025 growth was 2.2%, below 2024s 2.8%. Q3 2025 growth of 4.4% was actually lower than Bidens Q3 2023 (4.7%). Job growth under Trump year 1 (359k, 0.2%) was slower than Bidens final year (1.2M, 0.8%). Sources: [FactCheck.org](http://FactCheck.org), BEA, NYT.",
    content: "## Claim\nUnder my leadership, economic growth is exploding to numbers unheard of. Theyve never had them before. \u2014 President Donald Trump, Iowa, January 27, 2026.\n## Verdict: Mostly False\nBEA advance estimate (Feb 20, 2026) shows Q4 2025 GDP grew at just 1.4% annualized, down sharply from 4.4% in Q3 2025. Full-year 2025 growth was 2.2%, below 2024s 2.8%. The economy actually contracted in Q1 2025 (-0.6%). The Q3 2025 growth of 4.4% was below Bidens Q3 2023 figure of 4.7%.\n## Key Data\n- Q1 2025: -0.6%\n- Q2 2025: +3.8%\n- Q3 2025: +4.4%\n- Q4 2025: +1.4%\n- Full Year 2025: +2.2% (vs 2.8% in 2024)\n## Sources\n- [FactCheck.org](http://FactCheck.org) (Feb 19, 2026): [https://www.factcheck.org/2026/02/a-pre-sotu-guide-to-trumps-economic-claims/](https://www.factcheck.org/2026/02/a-pre-sotu-guide-to-trumps-economic-claims/)\n- BEA (Feb 20, 2026): [https://www.bea.gov/news/2026/gdp-advance-estimate-4th-quarter-and-year-2025](https://www.bea.gov/news/2026/gdp-advance-estimate-4th-quarter-and-year-2025)\n- NYT (Feb 23, 2026): [https://www.nytimes.com/2026/02/23/us/politics/trump-economy-fact-check.html](https://www.nytimes.com/2026/02/23/us/politics/trump-economy-fact-check.html)",
  },
  {
    id: "31005c7c-d6a6-81d2-b915-cea586cb5716",
    title: "Trump Says Supreme Court Tariff Ruling Made His Tariff Power More Powerful",
    url: "https://www.notion.so/31005c7cd6a681d2b915cea586cb5716",
    verdict: "False",
    category: "Economy",
    keyFigures: ["Trump"],
    reportDate: "2026-02-23",
    dateCovered: "2026-02-20",
    status: "Follow-Up Complete",
    followUpRequired: false,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "On Feb 20, 2026, SCOTUS 6-3 struck down IEEPA tariffs in Learning Resources v. Trump. Trump falsely claimed the ruling gave him MORE power. Roberts wrote IEEPA contains no reference to tariffs. Trump signed new 10% tariff under Section 122, capped at 150 days. Sources: CNN, SCOTUSblog, Reuters, CFR.",
    content: "## Claim\nWhile I am sure that they did not mean to do so, the Supreme Courts decision today made a presidents ability to both regulate trade and impose tariffs more powerful and more crystal clear rather than less. \u2014 President Donald Trump, February 20, 2026.\n## Verdict: False\nThe Supreme Courts 6-3 ruling in Learning Resources, Inc. v. Trump explicitly struck down Trumps IEEPA tariffs. Chief Justice Roberts wrote that IEEPA contains no reference to tariffs or duties. Trump responded by signing a new 10% global tariff under Section 122 of the Trade Act of 1974, which is capped at 150 days absent congressional approval.\n## Sources\n- CNN (Feb 20, 2026): [https://www.cnn.com/us/live-news/trump-administration-us-iran-02-20-26](https://www.cnn.com/us/live-news/trump-administration-us-iran-02-20-26)\n- SCOTUSblog (Feb 20, 2026): [https://www.scotusblog.com/2026/02/supreme-court-strikes-down-tariffs/](https://www.scotusblog.com/2026/02/supreme-court-strikes-down-tariffs/)\n- Reuters (Feb 21, 2026)\n- Council on Foreign Relations (Feb 23, 2026): [https://www.cfr.org/articles/after-the-supreme-court-ruling-what-is-next-for-trumps-tariffs](https://www.cfr.org/articles/after-the-supreme-court-ruling-what-is-next-for-trumps-tariffs)",
  },
  {
    id: "2eb05c7c-d6a6-815b-9e2a-f03775c15037",
    title: "US needs Greenland to prevent Russia/China control",
    url: "https://www.notion.so/2eb05c7cd6a6815b9e2af03775c15037",
    verdict: "Mostly False",
    category: "Foreign Policy",
    keyFigures: ["Trump"],
    reportDate: "2026-01-12",
    dateCovered: "2026-01-12",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "Trump renewed interest in acquiring Greenland, claiming national security imperative. Claims of imminent Russian/Chinese threat exaggerated and unsupported by evidence. Denmark firmly rejected sale. International community expressed concern about aggressive rhetoric.",
    content: "",
  },
  {
    id: "2eb05c7c-d6a6-81b6-a6c0-e85f927634bd",
    title: "DC had no murders in 7 months, safest city",
    url: "https://www.notion.so/2eb05c7cd6a681b6a6c0e85f927634bd",
    verdict: "False",
    category: "Criminal Justice",
    keyFigures: ["Trump"],
    reportDate: "2026-01-12",
    dateCovered: "2026-01-06",
    status: "Initial Coverage",
    followUpRequired: false,
    followUpReason: "None",
    fullDetails: "Trump claimed DC had no murders in 7 months and is safest city. Reality: DC recorded 127 homicides in 2025, including 5 in December alone. Crime expert Jeff Asher refuted safest city claim. Crime has decreased significantly but specific claims are false.",
    content: "",
  },
  {
    id: "2eb05c7c-d6a6-81ed-9311-fd750f99d653",
    title: "Renee Good was paid agitator/domestic terrorist",
    url: "https://www.notion.so/2eb05c7cd6a681ed9311fd750f99d653",
    verdict: "False",
    category: "Criminal Justice",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "2026-01-12",
    dateCovered: "2026-01-08",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Extremely Controversial",
    fullDetails: "Renee Good (37) killed by ICE agent in Minneapolis. Administration claimed she was part of leftwing network of paid agitators and domestic terrorist. No evidence supports these claims. News reports describe her as wife and community member.",
    content: "",
  },
  {
    id: "2eb05c7c-d6a6-81f4-8d8f-c74f30becbde",
    title: "$10 billion funding freeze to combat fraud",
    url: "https://www.notion.so/2eb05c7cd6a681f48d8fc74f30becbde",
    verdict: "Mixed",
    category: "Domestic Policy",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "2026-01-12",
    dateCovered: "2026-01-06",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Ongoing/Developing Story",
    fullDetails: "Trump administration froze \\$10B in social services funding to 5 Democratic states citing fraud. Federal judge granted temporary restraining order on Jan 9. While Minnesota fraud concerns are documented, broad freeze without due process deemed illegal.",
    content: "",
  },
  {
    id: "2eb05c7c-d6a6-81f6-9370-ffba84f55895",
    title: "Venezuela military operation was legal self-defense",
    url: "https://www.notion.so/2eb05c7cd6a681f69370ffba84f55895",
    verdict: "Mostly False",
    category: "Foreign Policy",
    keyFigures: ["Trump", "Cabinet Officials"],
    reportDate: "2026-01-12",
    dateCovered: "2026-01-03",
    status: "Follow-Up Pending",
    followUpRequired: true,
    followUpReason: "Extremely Controversial",
    fullDetails: "US military operation captured Venezuelan President Maduro on Jan 3. Administration claims legal under UN Charter Article 51 (self-defense). International law experts consensus: operation violates UN Charter. UN Secretary-General and allies condemned operation.",
    content: "",
  },
];

// Computed metrics
export const metrics = {
  totalReports: 38,
  truthRate: 18.4,
  falseRate: 68.4,
  truthCount: 7,
  falseCount: 26,
  mixedCount: 5,
  followUpRequired: 13,
  lastUpdated: "March 2, 2026",
  verdictDistribution: {
    "True": 7,
    "Mostly True": 0,
    "Mixed": 5,
    "Mostly False": 11,
    "False": 15,
  },
  categoryDistribution: {
    "Economy": 12,
    "Foreign Policy": 11,
    "Criminal Justice": 7,
    "Domestic Policy": 5,
    "Immigration/Border": 2,
    "Other": 1,
  },
  figureStats: {
    "Trump": { total: 37, falseCount: 25, truthCount: 7 },
    "Cabinet Officials": { total: 8, falseCount: 5, truthCount: 1 },
    "State Officials": { total: 2, falseCount: 0, truthCount: 1 },
    "Biden": { total: 1, falseCount: 1, truthCount: 0 },
    "Netanyahu": { total: 1, falseCount: 0, truthCount: 1 },
  },
};

export const VERDICT_COLORS: Record<Verdict, { bg: string; text: string; border: string; hex: string }> = {
  "True": { bg: "bg-emerald-100", text: "text-emerald-800", border: "border-emerald-400", hex: "#16A34A" },
  "Mostly True": { bg: "bg-lime-100", text: "text-lime-800", border: "border-lime-400", hex: "#65A30D" },
  "Mixed": { bg: "bg-amber-100", text: "text-amber-800", border: "border-amber-400", hex: "#CA8A04" },
  "Mostly False": { bg: "bg-orange-100", text: "text-orange-800", border: "border-orange-400", hex: "#EA580C" },
  "False": { bg: "bg-red-100", text: "text-red-800", border: "border-red-400", hex: "#DC2626" },
};

export const CATEGORY_COLORS: Record<string, string> = {
  "Economy": "#1E3A5F",
  "Immigration/Border": "#7C3AED",
  "Domestic Policy": "#0369A1",
  "Criminal Justice": "#B45309",
  "Foreign Policy": "#065F46",
  "Healthcare": "#BE185D",
  "Other": "#6B7280",
};
